# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-09 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20180709_2240'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comments',
            table=None,
        ),
    ]
