# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-04 16:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0006_auto_20180709_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comments_author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='comments_date',
            field=models.DateField(auto_now=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comments_text',
            field=models.TextField(verbose_name='Текст комментария'),
        ),
    ]
