# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-04 16:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20180804_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comments_author',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
