# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-04 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20180804_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='image'),
        ),
    ]
